INSERT INTO menu_items (id, name, price, kitchen_station, available) VALUES
('lasaniya_dhokla', 'Lasaniya Dhokla', 320.00, 'kathiyawadi', true),
('kathiyawadi_special', 'Kathiyawadi Special', 300.00, 'kathiyawadi', true),
('sev_khamani', 'Sev Khamani', 280.00, 'kathiyawadi', true),
('batata_vada', 'Batata Vada', 280.00, 'kathiyawadi', true),
('kothimbir_vadi', 'Kothimbir Vadi', 280.00, 'kathiyawadi', true),
('farali_sev_khaman', 'Farali Sev Khaman', 300.00, 'kathiyawadi', true),
('dahi', 'Dahi', 150.00, 'kathiyawadi', true),
('kadhi_bowl', 'Kadhi Bowl', 150.00, 'kathiyawadi', true),
('masala_khaman__sev_', 'Masala Khaman (Sev)', 210.00, 'kathiyawadi', true),
('punjabi_khaman__sev_', 'Punjabi Khaman (Sev)', 150.00, 'kathiyawadi', true),
('vagharela_khaman', 'Vagharela Khaman', 80.00, 'kathiyawadi', true),
('masala_khaman', 'Masala Khaman', 75.00, 'kathiyawadi', true),
('pakoda_khaman', 'Pakoda Khaman', 80.00, 'kathiyawadi', true),
('dahi_khaman', 'Dahi Khaman', 90.00, 'kathiyawadi', true),
('dahi_tikhari', 'Dahi Tikhari', 90.00, 'kathiyawadi', true),
('rotla__bhakhri_', 'Rotla (Bhakhri)', 28.00, 'kathiyawadi', true),
('lava_papad', 'Lava Papad', 28.00, 'kathiyawadi', true),
('swami_roti', 'Swami Roti', 15.00, 'kathiyawadi', true),
('math', 'Math', 20.00, 'kathiyawadi', true),
('kathiyawadi_roti_khaman', 'Kathiyawadi Roti Khaman', 388.00, 'kathiyawadi_special', true),
('kathiyawadi_special_combo', 'Kathiyawadi Special Combo', 300.00, 'kathiyawadi_special', true),
('sev_chaas_dhokli_combo', 'Sev Chaas Dhokli Combo', 320.00, 'kathiyawadi_special', true),
('methi_gota_sev_combo', 'Methi Gota Sev Combo', 380.00, 'kathiyawadi_special', true),
('dry_bhaji', 'Dry Bhaji', 300.00, 'kathiyawadi_special', true),
('lilva_papad', 'Lilva Papad', 340.00, 'kathiyawadi_special', true),
('masala_aloo', 'Masala Aloo', 260.00, 'kathiyawadi_special', true),
('lilva_methi_vada', 'Lilva Methi Vada', 320.00, 'kathiyawadi_special', true),
('gunda_achar', 'Gunda Achar', 320.00, 'kathiyawadi_special', true),
('rasawala_gunda_bateta', 'Rasawala Gunda Bateta', 323.00, 'kathiyawadi_special', true),
('lilva_sev_khaman', 'Lilva Sev Khaman', 320.00, 'kathiyawadi_special', true),
('bateta_sev_kathiyawadi', 'Bateta Sev Kathiyawadi', 320.00, 'kathiyawadi_special', true),
('lilva_gunda_bateta', 'Lilva Gunda Bateta', 323.00, 'kathiyawadi_special', true),
('methi_masala', 'Methi Masala', 320.00, 'kathiyawadi_special', true),
('lilva_rasawala_moria', 'Lilva Rasawala Moria', 320.00, 'kathiyawadi_special', true),
('kaju_kari', 'Kaju Kari', 470.00, 'kaju', true),
('kaju_paneer', 'Kaju Paneer', 470.00, 'kaju', true),
('kaju_masala', 'Kaju Masala', 480.00, 'kaju', true),
('kaju_curry', 'Kaju Curry', 480.00, 'kaju', true),
('kaju_mutter_masala', 'Kaju Mutter Masala', 480.00, 'kaju', true),
('kaju_butter_curry', 'Kaju Butter Curry', 480.00, 'kaju', true),
('kaju_butter_masala', 'Kaju Butter Masala', 518.00, 'kaju', true),
('kaju_kadhai', 'Kaju Kadhai', 518.00, 'kaju', true),
('kaju_handi', 'Kaju Handi', 530.00, 'kaju', true),
('veg_handi', 'Veg Handi', 320.00, 'vegetables', true),
('veg_kadhai', 'Veg Kadhai', 360.00, 'vegetables', true),
('veg_kolhapuri', 'Veg Kolhapuri', 350.00, 'vegetables', true),
('veg_hyderabadi', 'Veg Hyderabadi', 370.00, 'vegetables', true),
('veg_jaipuri', 'Veg Jaipuri', 350.00, 'vegetables', true),
('veg_tawa_masala', 'Veg Tawa Masala', 370.00, 'vegetables', true),
('veg_chatpata', 'Veg Chatpata', 380.00, 'vegetables', true),
('veg_makhanwala', 'Veg Makhanwala', 380.00, 'vegetables', true),
('veg_kaju_masala', 'Veg Kaju Masala', 380.00, 'vegetables', true),
('veg_bhuna_masala', 'Veg Bhuna Masala', 380.00, 'vegetables', true),
('veg_paneer_mix', 'Veg Paneer Mix', 410.00, 'vegetables', true),
('mix_vegetable', 'Mix Vegetable', 380.00, 'vegetables', true),
('veg_do_pyaza', 'Veg Do Pyaza', 380.00, 'vegetables', true),
('veg_achari', 'Veg Achari', 380.00, 'vegetables', true),
('veg_lahori', 'Veg Lahori', 380.00, 'vegetables', true),
('aloo_gobi', 'Aloo Gobi', 340.00, 'vegetables', true),
('paneer_butter_masala', 'Paneer Butter Masala', 390.00, 'paneer', true),
('shahi_paneer', 'Shahi Paneer', 420.00, 'paneer', true),
('paneer_kadhai', 'Paneer Kadhai', 390.00, 'paneer', true),
('paneer_handi', 'Paneer Handi', 400.00, 'paneer', true),
('paneer_makhani', 'Paneer Makhani', 400.00, 'paneer', true),
('paneer_tawa', 'Paneer Tawa', 400.00, 'paneer', true),
('paneer_achari', 'Paneer Achari', 420.00, 'paneer', true),
('paneer_bhuna', 'Paneer Bhuna', 430.00, 'paneer', true),
('paneer_curry', 'Paneer Curry', 450.00, 'paneer', true),
('paneer_do_pyaza', 'Paneer Do Pyaza', 450.00, 'paneer', true),
('tomato_soup', 'Tomato Soup', 120.00, 'soup', true),
('veg_manchow_soup', 'Veg Manchow Soup', 130.00, 'soup', true),
('hot_and_sour_soup', 'Hot and Sour Soup', 130.00, 'soup', true),
('sweet_corn_soup', 'Sweet Corn Soup', 135.00, 'soup', true),
('lemon_coriander_soup', 'Lemon Coriander Soup', 145.00, 'soup', true),
('veg_manchurian', 'Veg Manchurian', 160.00, 'chinese', true),
('veg_lollipop', 'Veg Lollipop', 160.00, 'chinese', true),
('crispy_veg', 'Crispy Veg', 160.00, 'chinese', true),
('veg_fried_rice', 'Veg Fried Rice', 160.00, 'chinese', true),
('veg_noodles', 'Veg Noodles', 160.00, 'chinese', true),
('veg_schezwan', 'Veg Schezwan', 170.00, 'chinese', true),
('paneer_chilli', 'Paneer Chilli', 180.00, 'chinese', true),
('paneer_manchurian', 'Paneer Manchurian', 210.00, 'chinese', true),
('plain_tandoori_roti', 'Plain Tandoori Roti', 35.00, 'tandoor', true),
('butter_tandoori_roti', 'Butter Tandoori Roti', 40.00, 'tandoor', true),
('plain_tandoori_paratha', 'Plain Tandoori Paratha', 45.00, 'tandoor', true),
('butter_tandoori_paratha', 'Butter Tandoori Paratha', 50.00, 'tandoor', true),
('plain_kulcha', 'Plain Kulcha', 50.00, 'tandoor', true),
('butter_kulcha', 'Butter Kulcha', 50.00, 'tandoor', true),
('plain_naan', 'Plain Naan', 50.00, 'tandoor', true),
('butter_naan', 'Butter Naan', 60.00, 'tandoor', true),
('cheese_naan', 'Cheese Naan', 95.00, 'tandoor', true),
('cheese_garlic_naan', 'Cheese Garlic Naan', 95.00, 'tandoor', true),
('dal_fry', 'Dal Fry', 130.00, 'dal', true),
('dal_tadka', 'Dal Tadka', 150.00, 'dal', true),
('dal_makhani', 'Dal Makhani', 150.00, 'dal', true),
('dal_kolhapuri', 'Dal Kolhapuri', 150.00, 'dal', true),
('jeera_rice', 'Jeera Rice', 110.00, 'rice', true),
('veg_pulav', 'Veg Pulav', 150.00, 'rice', true),
('veg_biryani', 'Veg Biryani', 155.00, 'rice', true),
('kaju_pulav', 'Kaju Pulav', 165.00, 'rice', true),
('hyderabadi_biryani', 'Hyderabadi Biryani', 160.00, 'rice', true),
('chole_bhature', 'Chole Bhature', 150.00, 'cholebhature', true),
('special_chole_bhature', 'Special Chole Bhature', 150.00, 'cholebhature', true),
('paneer_chole_bhature', 'Paneer Chole Bhature', 160.00, 'cholebhature', true),
('extra_bhature', 'Extra Bhature', 50.00, 'cholebhature', true),
('buttermilk', 'Buttermilk', 20.00, 'beverages', true),
('salted_papad', 'Salted Papad', 20.00, 'beverages', true),
('fried_papad', 'Fried Papad', 30.00, 'beverages', true),
('fried_mirch', 'Fried Mirch', 20.00, 'beverages', true),
('tomato_salad', 'Tomato Salad', 50.00, 'beverages', true),
('water_bottle', 'Water Bottle', 20.00, 'beverages', true),
('gulab_jamun', 'Gulab Jamun', 30.00, 'desserts', true),
('ladoo', 'Ladoo', 30.00, 'desserts', true)
ON CONFLICT (id) DO NOTHING;